<a href="https://colab.research.google.com/github/sarthaksandilya01/data-science/blob/main/arithmeticop_on_marrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [2]:
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
arr2=np.array([[9,8,7],[6,5,4],[3,2,1]])

In [4]:
arr3=np.array([[9,8,7,5],[6,5,4,2],[3,2,1,5]])

In [5]:
arr1


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
arr2

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [7]:
arr3

array([[9, 8, 7, 5],
       [6, 5, 4, 2],
       [3, 2, 1, 5]])

In [8]:
arr1+arr2

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [9]:
arr1*arr2

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

In [12]:
arr1.dot(arr2)

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [13]:
arr=np.array([1,2,3,4])

In [15]:
arr[:-2]

array([1, 2])