<a href="https://colab.research.google.com/github/sarthaksandilya01/data-science/blob/main/arithmetic_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


updating all elements of an array 


In [2]:
arr=np.array([1,2,3,4,5,6])

In [3]:
arr


array([1, 2, 3, 4, 5, 6])

In [4]:
print(arr+1)

[2 3 4 5 6 7]


In [5]:
print(arr-1)

[0 1 2 3 4 5]


In [6]:
print(arr*5)

[ 5 10 15 20 25 30]


In [7]:
print(arr**3)

[  1   8  27  64 125 216]


In [8]:
arr=arr+1

In [9]:
arr


array([2, 3, 4, 5, 6, 7])

In [10]:
arr+=1

In [11]:
arr


array([3, 4, 5, 6, 7, 8])

In [13]:
arr.max()

8

In [14]:
arr.min()

3

In [17]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [18]:
arr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
arr.max(axis=0)

array([7, 8, 9])

In [21]:
arr.max(axis=1)

array([3, 6, 9])

In [22]:
arr.min(axis=0)

array([1, 2, 3])

In [23]:
arr.sum()

45