<a href="https://colab.research.google.com/github/sarthaksandilya01/data-science/blob/main/automating.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [2]:
lst=[1,2,3,4,5,6,7,8,9,10]



In [18]:
q=0
for i in lst:
  if(i>5):
    print(i)
    q+=1

print(q)



6
7
8
9
10
5


In [10]:
lst=np.array([1,2,3,4,5,6,7,8,9,10])

In [11]:
lst

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
lst>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [19]:
print(len(lst))

10


In [20]:
print(len(lst[lst>5]))

5


In [21]:
print(lst[lst>5])

[ 6  7  8  9 10]
