<a href="https://colab.research.google.com/github/sarthaksandilya01/data-science/blob/main/intro_to_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install numpy


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
import numpy as np


In [3]:
np


<module 'numpy' from '/usr/local/lib/python3.10/dist-packages/numpy/__init__.py'>

In [5]:
lst=[1,2,3]


In [6]:
type(lst)

list

In [8]:
arr=np.array(lst)
arr

array([1, 2, 3])

In [9]:
type(arr)

numpy.ndarray

In [10]:
arr.ndim

1

In [11]:
arr.shape


(3,)

In [12]:
arr.size

3

In [13]:
arr.dtype


dtype('int64')

generate 0's and 1's arrays of any size

In [15]:
zeros=np.zeros((3,4))

In [16]:
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
ones=np.ones((5,3))

In [18]:
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])