<a href="https://colab.research.google.com/github/sarthaksandilya01/data-science/blob/main/merging.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [2]:
arr1=np.array([[1,2,3,4],[5,6,7,8]])

In [3]:
arr2=np.array([[8,7,6,5],[4,3,2,1]])

In [4]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
arr2


array([[8, 7, 6, 5],
       [4, 3, 2, 1]])

In [7]:
np.vstack((arr1,arr2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [8]:
np.hstack((arr1,arr2))

array([[1, 2, 3, 4, 8, 7, 6, 5],
       [5, 6, 7, 8, 4, 3, 2, 1]])

In [9]:
arr=np.concatenate((arr1,arr2),axis=0)

In [10]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [12]:
arr=np.concatenate((arr1,arr2),axis=1)

In [13]:
arr

array([[1, 2, 3, 4, 8, 7, 6, 5],
       [5, 6, 7, 8, 4, 3, 2, 1]])

In [15]:
np.hsplit(arr,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[8, 7, 6, 5],
        [4, 3, 2, 1]])]

In [ ]:
f