<a href="https://colab.research.google.com/github/sarthaksandilya01/data-science/blob/main/reshape_and_random.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

reshape and random number generator'

In [1]:
import numpy as np


In [4]:
np.random.random((3,3))

array([[0.97068084, 0.72740335, 0.01656372],
       [0.88090734, 0.68651971, 0.28954555],
       [0.89224891, 0.74389183, 0.84282768]])

In [5]:
np.random.random()

0.35714380924529465

In [6]:
np.arange(1,10,3)

array([1, 4, 7])

1 included and 10 excluded

In [7]:
np.linspace(1,7,10)

array([1.        , 1.66666667, 2.33333333, 3.        , 3.66666667,
       4.33333333, 5.        , 5.66666667, 6.33333333, 7.        ])

In [8]:
arr=np.random.random((4,3))


In [9]:
arr


array([[0.37629445, 0.70604229, 0.19573418],
       [0.204705  , 0.73408764, 0.08804415],
       [0.35637583, 0.86769546, 0.34981506],
       [0.13805763, 0.71671087, 0.66724382]])

In [10]:
np.reshape(arr,(3,4))

array([[0.37629445, 0.70604229, 0.19573418, 0.204705  ],
       [0.73408764, 0.08804415, 0.35637583, 0.86769546],
       [0.34981506, 0.13805763, 0.71671087, 0.66724382]])

In [12]:
arr.flatten()

array([0.37629445, 0.70604229, 0.19573418, 0.204705  , 0.73408764,
       0.08804415, 0.35637583, 0.86769546, 0.34981506, 0.13805763,
       0.71671087, 0.66724382])