<a href="https://colab.research.google.com/github/sarthaksandilya01/data-science/blob/main/slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5,6,7,8])

In [3]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
arr[3:]

array([4, 5, 6, 7, 8])

In [5]:
arr[:-3]

array([1, 2, 3, 4, 5])

In [6]:
arr[3:-3]

array([4, 5])

In [8]:
arr1=np.array([[1,2,3,4],[5,6,7,8],[8,7,6,5],[4,3,2,1]])

In [9]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [11]:
arr1[3,1]

3

In [13]:
arr1[1:,1:]

array([[6, 7, 8],
       [7, 6, 5],
       [3, 2, 1]])